### ISSUE TITLE
求助：推理可视化结果很差

### ISSUE THREAD

**Issue by zz-2024** [xb534/SED#20]
我使用demo/demo_for_vis.py对datasets/ADEChallengeData2016/images/training/ADE_train_00000001.jpg"(来自ADE),"datasets/imgs/2007_000175.jpg“（来自VOC），但是推理的结果非常差，是我使用错误吗？
配置文件主要的修改部分：
```
WEIGHTS: "/home/ccc/projects/sed_model_base.pth"
CLIP_PRETRAINED_WEIGHTS: ""
TEST_CLASS_JSON: "datasets/voc20.json" # XXX: 从coco.json修改为voc.json，类别数从171->20
```
模型在cpu上进行推理。
配置文件的完整内容：
```
_BASE_: config.yaml
MODEL:
  META_ARCHITECTURE: "SED"
  BACKBONE:
    NAME: "CLIP"
  WEIGHTS: "/home/ccc/projects/sed_model_base.pth"
  ENC:
    CLIP_MODEL_NAME: "convnext_base_w_320"
    CLIP_PRETRAINED_WEIGHTS: ""
    EMBED_DIM: 768
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  SEM_SEG_HEAD:
    NAME: "SEDHead"
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
    IGNORE_VALUE: 255
    NUM_CLASSES: 171
    TRAIN_CLASS_JSON: "datasets/coco.json"
    TEST_CLASS_JSON: "datasets/voc20.json" # XXX: 从coco.json修改为voc.json，类别数从171->20
    CLIP_PRETRAINED: "Convnext-B"
    PROMPT_DEPTH: 0
    PROMPT_LENGTH: 0
    TEXT_GUIDANCE_DIM: 0
    TEXT_GUIDANCE_PROJ_DIM: 0
    APPEARANCE_GUIDANCE_DIM: 1024
    APPEARANCE_GUIDANCE_PROJ_DIM: 128
    DECODER_DIMS: [64, 32, 16]
    DECODER_GUIDANCE_DIMS: [512, 256, 128]
    DECODER_GUIDANCE_PROJ_DIMS: [32, 16, 8]
    NUM_LAYERS: 2
    NUM_HEADS: 4
    HIDDEN_DIMS: 128
    POOLING_SIZES: [2, 2]
    FEATURE_RESOLUTION: [24, 24]
    WINDOW_SIZES: 12
    ATTENTION_TYPE: "linear"
    CNEXT_TYPE: "V1"
    KERNEL_SIZE: [9, 9, 9]
    CLIP_FINETUNE: "full"
  PROMPT_ENSEMBLE_TYPE: "imagenet" # 无法修改，因为作者提供的预训练权重就是针对80个text templates的
INPUT:
  MIN_SIZE_TRAIN: (768, )
  MAX_SIZE_TRAIN: 2666
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  MIN_SIZE_TEST: 640
  CROP:
    ENABLED: True
    TYPE: "absolute"
    SIZE: (768, 768)
  SIZE_DIVISIBILITY: 768
  FORMAT: "RGB"
  DATASET_MAPPER_NAME: "mask_former_semantic"
SOLVER:
  IMS_PER_BATCH: 4 
  LR_SCHEDULER_NAME: WarmupCosineLR
  BASE_LR: 0.0002
  MAX_ITER: 80000
  BACKBONE_MULTIPLIER: 0.0
  CLIP_MULTIPLIER: 0.01
TEST:
  EVAL_PERIOD: 10000
  FAST_INFERENCE: False
  TOPK: 1 # ?
  
```
推理结果：
![image](https://github.com/xb534/SED/assets/170588746/15c4edcc-2802-40df-babb-1bc34e764bd2)
![image](https://github.com/xb534/SED/assets/170588746/9d9c90f8-a1cf-42f4-9207-8717b44a9fa5)
除此之外，使用coco.json作为TEST_CLASS_JSON，效果还能看得过去。
![image](https://github.com/xb534/SED/assets/170588746/d20677ce-4c4a-4a5f-9b77-7d1e669c9363)
